SCREENWIDTH = 18
SCREENHEIGHT = 18
TICKRATE = 100000  # frame per sec
velocity = 1  # pixels per frame
apple_size = 1  # pixels
snake_size = 1  # pixels
positioner = snake_size//velocity
population_size = 100
parents_size = 10
idle_time = 1500  # ms
mutation_rate = 300  # per mile
mutation_frequency = 30  # percent
crossing_probability = 10  # percent
epoch_number = 1000
